# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 747784807058b29fcfacef6fc985bf6820755eb30eaac14b8bcc84c4689c0d3696ee2ec2b4c488eeeb3f7fbbf59a080771831cd65cd141defe5a632d508242dd

test:
  secret_key_base: bd8f17931f1398a0b41d00fcca1417619d5b5243c87f39740e662f0cbd2f380da0c73a69c2dcb2f880633d19dfad76e82bbcce7cc5c540a1669ffed4cd120dd4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
